config/routes.rb
Rails.application.routes.draw do
  get 'dashboard/index'

  get 'booking/index'

  get 'booking/new'
  post 'booking/create'
  get 'booking/previous_booking_list'

  get 'homes/index'
  get 'homes/new'
  get 'welcome/index'
  delete 'welcome/destroy'
  get 'welcome/new'
  post 'welcome/create'
  root 'homes#index'
  devise_for :users

  resources :charges
  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader 
	belongs_to :user
	has_one :category
	has_many :booking

	def self.search(search)
		if search
			find(:all, :conditions => [:name => search])
		else
			find(:all)
		end
	end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :events
  has_many :bookings

  def quantity_available(quantity_count,event_id)
		p 'event details'
		p event = Event.find_by(id: event_id)
		p 'booing quantity'
		p booking_quantity = Booking.where(event_id: event.id).sum(:quantity)
		p 'balance quantity'
		p bal = event.ticket - booking_quantity
		if bal > 0
			return true
		else
			return false
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  private
	def sign_up_params
		params.require(:user).permit(:username, :attachment, :email, :password, :password_confirmation)
	end

	def account_update_params
		params.require(:user).permit( :username, :attachment, :email, :password, :password_confirmation, :current_password)
	end
end

app/controllers/booking_controller.rb
class BookingController < ApplicationController
	before_action :authenticate_user!
  before_action :user_method
	
  def index
    # if session[:booking_id].present?
  		# p @booking = Booking.where(user_id: current_user.id).where(id: session[:booking_id])
    #   @event = Event.find_by(id: @booking.event_id)
    # end
    @booking = Booking.find_by(id: params[:booking])
    @event = Event.find_by(id: @booking.event_id)
    # @bookings = Booking.where(user_id: current_user.id)

  end

  def new
  		@booking = Booking.new
      @event = Event.find_by(id: params[:event_id])
      @bookings_quantity = Booking.where(event_id: @event.id).sum(:quantity)

  end

  def create
    @event_ticket_amt = Event.find_by(id: params[:booking][:event_id]).ticket_amount
    if @user.quantity_available(params[:booking][:quantity],params[:booking][:event_id])
    	@booking = Booking.new(params.require(:booking).permit(:quantity,:amount,:event_id,:user_id,:status))
  		if @booking.save
        p @booking
        @booking.update_attributes(amount: @booking.quantity * @event_ticket_amt )
        # session[:booking_id] = @booking.id
        flash[:notice] = "Ticket successfully Booked"
    		redirect_to booking_index_path(booking: @booking)
     end
    else
      redirect_to booking_new_path
    end
  end

  def previous_booking_list
    @bookings = Booking.where(user_id: current_user.id)

    # respond_to do |format|
    #   format.html
    #   format.pdf do
    #     render :pdf => "previous_booking_list.html.erb",
    #     :layout => "pdf",
    #     :template => "booking/pdf_previous_booking_list.html.erb",
    #     margin:  {   left: "10mm"}
    #   end 
    # end

    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "previous_booking_list"
      end
    end
  end

  private
    def user_method
      @user = User.find_by(id: current_user.id)
    end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

	def new
	end

	def create
	  # Amount in cents
	  @amount = 500

	  customer = Stripe::Customer.create(
	  	:email => params[:stripeEmail],
	  	:source  => params[:stripeToken]
	  	)

	  charge = Stripe::Charge.create(
	  	:customer    => customer.id,
	  	:amount      => @amount,
	  	:description => 'Rails Stripe customer',
	  	:currency    => 'usd'
	  	)

	rescue Stripe::CardError => e
		flash[:error] = e.message
		redirect_to new_charge_path
	end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :authenticate_user!
  def index
  end
end

app/controllers/event_controller.rb
class EventController < ApplicationController
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
		if params[:search]
			@events = Event.where(name: params[:search])
		else
			@events = Event.all
		end
	end
	
	def new
		@event = Event.new()
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_action :authenticate_user!


	def index
		if params[:search]
			@my_events = Event.where(name: params[:search])
		else
			@events = Event.all
			@my_events = Event.where(user_id: current_user.id)
			@other_events = Event.where.not(user_id: current_user.id)
		end
	end
	
	def new
		@event = Event.new
	end

	def create
		@event = Event.new(params.require(:event).permit(:name,:attachment,:category_id,:user_id,:place,:ticket,:ticket_amount,:expire_date))
		@event.save
		flash[:notice] = "Event successfully created"
		redirect_to welcome_index_path
	end
	def destroy
		@event = Event.find(params[:id])
		@event.destroy
		flash[:notice] = "Event successfully Deleted"
		redirect_to welcome_index_path
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	def previous_event(book)
		event = Event.find_by_id(book.event_id)
		event.present? ? event.name : 'nil'
	end
end

app/helpers/booking_helper.rb
module BookingHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/booking/index.html.erb
<div class="container">
	<% if flash[:notice] %>
	<div class="alert alert-success" role="alert">
		<%= flash[:notice] %>
	</div>
	<% end %>
	<h1>Ticket Booking Details</h1>

	<%= image_tag @event.attachment_url ,:size => "100x100"%><br>
	Event name:<%=  @event.name %><br>
	Ticket Quantity:<%= @booking.quantity %><br>
	Per Ticket : <%= @event.ticket_amount %><br>
	Total Amount : <%= @booking.amount %><br>
	Date : <%= @booking.created_at.to_date %><br>
	Time : <%= @booking.created_at.to_time %><br>
	<h3 style="color:#64FE2E"><%= @booking.status %></h3><br>
	<%=link_to "Previous Booking Details", booking_previous_booking_list_path, :class => "btn btn-primary"%>
</div>

app/views/booking/new.html.erb
<div class="container">
	<h1>welcome to Bookmyshow</h1>

<h3>Event name:<%= @event.name %></h3>
<h1><%= image_tag @event.attachment_url.to_s, size: "100x100" %></h1>
<% if @bookings_quantity < @event.ticket%>
	<%= form_for @booking, url: booking_create_path(@booking) do |f|%>
		No of tickets:<%= f.text_field :quantity %>
		<%= f.hidden_field :status, value: "Ticket booked" %>
		<%= f.hidden_field :event_id, value: params[:event_id]%>
		<%= f.hidden_field :user_id, value: current_user.id %>
		<%= f.submit %>
	<% end %>
<%else%>
	<pre>
		Ticket has been exprited
	</pre>
<%end%>
</div>

app/views/booking/pdf_previous_booking_list.html.erb
hhhhhhh

app/views/booking/previous_booking_list.html.erb
<div class="container">
	<div class="col-md-12">
		<h3>Previous Booking List</h3>
		<table class="table">
			<thead>
				<tr>
				<th>Event Name</th>
				<th>No Of Tickets</th>
				<th>Total Amount</th>
				<th>Ticket Status</th>
				<th>Date</th>
				<th>Time</th>
				</tr>
			</thead>
			<% @bookings.each do |b| %>
			<tbody>
				<tr>
					<td><%= previous_event(b) %></td>
					<td><%= b.quantity %></td>
					<td><%= b.amount %></td>
					<td style="color:#64FE2E"><%= b.status %></td>
					<td><%= b.created_at.to_date %></td>
					<td><%= b.created_at.to_time %></td>
				</tr>
			</tbody>
			<%end%>
		</table>
	</div>	
</div>

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong>$5.00</strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/dashboard/index.html.erb
<body class="hold-transition skin-blue sidebar-mini">
      <aside class="main-sidebar">

        <!-- sidebar: style can be found in sidebar.less -->
        <section class="sidebar">

          <!-- Sidebar user panel (optional) -->
          <div class="user-panel">
            <div class="pull-left image">
              <img src="/assets/user2-160x160.jpg" class="img-circle" alt="User Image">
            </div>
            <div class="pull-left info">
              <p>Alexander Pierce</p>
              <!-- Status -->
              <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
            </div>
          </div>

          <!-- search form (Optional) -->
          <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
              <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
              </span>
            </div>
          </form>
          <!-- /.search form -->

          <!-- Sidebar Menu -->
          <ul class="sidebar-menu">
            <li class="header">HEADER</li>
            <!-- Optionally, you can add icons to the links -->
            <li class="active"><a href="#"><i class="fa fa-link"></i> <span>Link</span></a></li>
            <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li>
            <li class="treeview">
              <a href="#"><i class="fa fa-link"></i> <span>Multilevel</span> <i class="fa fa-angle-left pull-right"></i></a>
              <ul class="treeview-menu">
                <li><a href="#">Link in level 2</a></li>
                <li><a href="#">Link in level 2</a></li>
              </ul>
            </li>
          </ul><!-- /.sidebar-menu -->
        </section>
        <!-- /.sidebar -->
      </aside>

      <!-- Content Wrapper. Contains page content -->
      <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
          <h1>
            Page Header
            <small>Optional description</small>
          </h1>
          <ol class="breadcrumb">
            <li><%= link_to "Home", root_path %></li>
            <li class="active">Here</li>
          </ol>
        </section>

        <!-- Main content -->
        <section class="content">

          <!-- Your Page Content Here -->

        </section><!-- /.content -->
      </div><!-- /.content-wrapper -->

      <!-- Main Footer -->
      <footer class="main-footer">
        <!-- To the right -->
        <div class="pull-right hidden-xs">
          Anything you want
        </div>
        <!-- Default to the left -->
        <strong>Copyright &copy; 2015 <a href="#">Company</a>.</strong> All rights reserved.
      </footer>

      <!-- Control Sidebar -->
      <aside class="control-sidebar control-sidebar-dark">
        <!-- Create the tabs -->
        <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
          <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
          <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
        </ul>
        <!-- Tab panes -->
        <div class="tab-content">
          <!-- Home tab content -->
          <div class="tab-pane active" id="control-sidebar-home-tab">
            <h3 class="control-sidebar-heading">Recent Activity</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <i class="menu-icon fa fa-birthday-cake bg-red"></i>
                  <div class="menu-info">
                    <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>
                    <p>Will be 23 on April 24th</p>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

            <h3 class="control-sidebar-heading">Tasks Progress</h3>
            <ul class="control-sidebar-menu">
              <li>
                <a href="javascript::;">
                  <h4 class="control-sidebar-subheading">
                    Custom Template Design
                    <span class="label label-danger pull-right">70%</span>
                  </h4>
                  <div class="progress progress-xxs">
                    <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
                  </div>
                </a>
              </li>
            </ul><!-- /.control-sidebar-menu -->

          </div><!-- /.tab-pane -->
          <!-- Stats tab content -->
          <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div><!-- /.tab-pane -->
          <!-- Settings tab content -->
          <div class="tab-pane" id="control-sidebar-settings-tab">
            <form method="post">
              <h3 class="control-sidebar-heading">General Settings</h3>
              <div class="form-group">
                <label class="control-sidebar-subheading">
                  Report panel usage
                  <input type="checkbox" class="pull-right" checked>
                </label>
                <p>
                  Some information about this general settings option
                </p>
              </div><!-- /.form-group -->
            </form>
          </div><!-- /.tab-pane -->
        </div>
      </aside><!-- /.control-sidebar -->
      <!-- Add the sidebar's background. This div must be placed
           immediately after the control sidebar -->
      <div class="control-sidebar-bg"></div>
    </div><!-- ./wrapper -->
  </body>
</html>

app/views/homes/index.html.erb
<div id="overlay">
  <div id="progstat"></div>
  <div id="progress"></div>
</div>
<div class="container">
  <% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
  <% end %>
  <!-- Portfolio Item Heading -->
  <%= form_tag homes_index_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
  <% end %>
  <hr>
  <div class="row">
    <div class="col-lg-12">
     <h1 class="page-header">Bookmyshow
      <small>Here Book Your Tickets</small>
    </h1>
  </div>
  <!-- /.row -->

  <!-- Portfolio Item Row -->
  <div class="row">
    <div class="col-md-8">
     <%= render "homes/slider" %>
   </div>

   <div class="col-md-4">
     <h3>Bookmyshow Description</h3>
     <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam viverra euismod odio, gravida pellentesque urna varius vitae. Sed dui lorem, adipiscing in adipiscing et, interdum nec metus. Mauris ultricies, justo eu convallis placerat, felis enim.</p>
     <h3>Event Details</h3>
     <ul>
      <li>Select Event</li>
      <li>Choose Category</li>
      <li>Book Your Tickets</li>
      <li>Enjoy The Show</li>
    </ul>
  </div>

</div>
<!-- /.row -->
<!-- Related Projects Row -->
<div class="row">

  <div class="col-lg-12">
   <h3 class="page-header">All Events</h3>
 </div>
 <% @events.each do |e|%>
 <div class="col-sm-3 col-xs-6 top-align">
   <% if e.attachment.present? %>
   <%= image_tag e.attachment_url.to_s,:size => "280x180"%>
   <% else%>
   <%= image_tag '05.jpg',:size => "280x180"%>
   <% end %>
   <div class="caption">
    <h3><%= e.name %></h3>
    <p><b>Category</b>:<%= Category.find_by(id: e.category_id).name %></p>
    <p><b>Total Tickets</b>:<%= e.ticket %></p>
    <p><b>Ticket Amount</b>:<%= e.ticket_amount %></p>
    <p><b>Expiry Date</b>:<%= e.expire_date %></p>
    <%= link_to "Book Now!", booking_new_path(event_id: e.id), :class => "btn btn-primary" %>
  </div>
</div>
<%end%>


</div>
<!-- /.row -->

<hr>

<!-- Footer -->
<footer>
  <div class="row">
   <div class="col-lg-12">
    <p>Copyright &copy; Ticketshop 2014</p>
  </div>
</div>
<!-- /.row -->
</footer>

app/views/homes/new.html.erb
<%= form_for @event, url: homes_create_path(@event) do |e| %>
	name:
	<%= e.text_field :name %>
	<%= e.select :category_id, Category.all.map{|m| [m.name,m.id]}%>
	<%= e.hidden_field :user_id, value: current_user.id %>
	<%= e.submit %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookmyshow</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <%= csrf_meta_tags %>
</head>
<body>
  <% unless controller_name=="dashboard" or controller_name=="sessions" or controller_name=="registrations"%>
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'Bookmyshow', root_path ,:class => 'navbar-brand'%>
      </div>
      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li>
            <%= link_to 'welcome', welcome_index_path %>
          </li>
          <% if user_signed_in?%>
          <li>
            <%= link_to "Signout", destroy_user_session_path, method: :delete %>
          </li>
          <li>
            <%= link_to "Dashboard", dashboard_index_path %>
          </li>
          <% end %>
        </ul>
      </div>
      <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
  </nav>
  <%end%>
  <%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<div class="container">
	<% if flash[:notice] %>
	<div class="alert alert-success" role="alert">
		<%= flash[:notice] %>
	</div>
	<% end %>
	<%= link_to 'New Event', welcome_new_path,:class => "btn btn-info"  %>
	<hr>

	<%= form_tag welcome_index_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :search, params[:search] %>
		<%= submit_tag "Search", :name => nil %>
	</p>
	<% end %>

	<div class="row">

		<div class="col-md-12">
			<h3 class="page-header">My Events</h3>
		</div>
		<% if @my_events.present? %>
		<% @my_events.each do |m|%>
		<div class="col-sm-3 col-xs-6 top-align">
			<% if m.attachment.present? %>
			<%= image_tag m.attachment_url.to_s,:size => "280x180"%>
			<% else%>
			<%= image_tag '05.jpg',:size => "280x180"%>
			<% end %>
			<div class="caption">
				<h3><%= m.name %></h3>
				<p><b>Category</b>:<%= Category.find_by(id: m.category_id).name %></p>
				<p><b>Total Tickets</b>:<%= m.ticket %></p>
				<p><b>Ticket Amount</b>:<%= m.ticket_amount %></p>
				<p><b>Expiry Date</b>:<%= m.expire_date %></p>
				<%= link_to "Book Now!", booking_new_path(event_id: m.id), :class => "btn btn-primary" %><%= link_to 'Destroy', { action: :destroy, id: m.id }, method: :delete, data: { confirm: 'Are you sure?' },:class => "btn btn-danger right-align" %>
			</div>
		</div>
		<%end%>
		<%else%>
		<pre>No events</pre>
		<%end%>
	</div>

	<hr>

	<div class="row">

		<div class="col-md-12">
			<h3 class="page-header">Other Events</h3>
		</div>
		<% if @other_events.present? %>
		<% @other_events.each do |o|%>
		<div class="col-sm-3 col-xs-6 top-align">
			<%= image_tag o.attachment_url.to_s,:size => "280x180"%><br>
			<div class="caption">
				<h3><%= o.name %></h3>
				<p><b>Category</b>:<%= Category.find_by(id: o.category_id).name %></p>
				<p><b>Total Tickets</b>:<%= o.ticket %></p>
				<p><b>Ticket Amount</b>:<%= o.ticket_amount %></p>
				<p><b>Expiry Date</b>:<%= o.expire_date %></p>
				<%= link_to "Book Now!", booking_new_path(event_id: o.id), :class => "btn btn-primary" %>
			</div>
		</div>
		<%end%>
		<%else%>
		<pre>No events</pre>
		<%end%>

	</div>

	<hr>

	<!-- Footer -->
	<footer>
		<div class="row">
			<div class="col-lg-12">
				<p>Copyright &copy; Ticketshop 2014</p>
			</div>
		</div>
		<!-- /.row -->
	</footer>
</div>

app/views/welcome/new.html.erb
<div class="row">
	<div class="col-md-12 col-sm-12 col-xs-12">
		<div class="x_panel">
			<div class="x_content">
				<br />
				<%= form_for @event, url: welcome_create_path(@event) do |e| %>
				Name:<%= e.text_field :name %><br>
				<%= e.file_field :attachment %><br>
				<%= e.select :category_id, Category.all.map{|m| [m.name,m.id]}%><br>
				Place:<%= e.text_field :place %><br>
				Total Ticket Count:<%= e.text_field :ticket %><br>
				Ticket Amount(each 1):<%= e.text_field :ticket_amount%><br>
				Expiry Date:<%= e.date_field :expire_date%><br>
				<%= e.hidden_field :user_id, value: current_user.id %>
				<%= e.submit%>
				<%end%>
			</div>
		</div>
	</div>
</div>
<div class="col-md-12 col-sm-12 col-xs-12">
	<div class="x_panel">
		<div class="x_content">
			<br />
			<form id="demo-form2" data-parsley-validate class="form-horizontal form-label-left">

				<div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12" for="first-name">First Name <span class="required">*</span>
					</label>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input type="text" id="first-name" required="required" class="form-control col-md-7 col-xs-12">
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12" for="last-name">Last Name <span class="required">*</span>
					</label>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input type="text" id="last-name" name="last-name" required="required" class="form-control col-md-7 col-xs-12">
					</div>
				</div>
				<div class="form-group">
					<label for="middle-name" class="control-label col-md-3 col-sm-3 col-xs-12">Middle Name / Initial</label>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="middle-name" class="form-control col-md-7 col-xs-12" type="text" name="middle-name">
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12">Gender</label>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<div id="gender" class="btn-group" data-toggle="buttons">
							<label class="btn btn-default" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
								<input type="radio" name="gender" value="male"> &nbsp; Male &nbsp;
							</label>
							<label class="btn btn-primary active" data-toggle-class="btn-primary" data-toggle-passive-class="btn-default">
								<input type="radio" name="gender" value="female" checked=""> Female
							</label>
						</div>
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12">Date Of Birth <span class="required">*</span>
					</label>
					<div class="col-md-6 col-sm-6 col-xs-12">
						<input id="birthday" class="date-picker form-control col-md-7 col-xs-12" required="required" type="text">
					</div>
				</div>
				<div class="form-group">
					<label class="control-label col-md-3 col-sm-3 col-xs-12">Select</label>
					<div class="col-md-9 col-sm-9 col-xs-12">
						<select class="form-control">
							<option>Choose option</option>
							<option>Option one</option>
							<option>Option two</option>
							<option>Option three</option>
							<option>Option four</option>
						</select>
					</div>
				</div>
				<div class="ln_solid"></div>
				<div class="form-group">
					<div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
						<button type="submit" class="btn btn-primary">Cancel</button>
						<button type="submit" class="btn btn-success">Submit</button>
					</div>
				</div>

			</form>
		</div>
	</div>
</div>